services:
  account:
    image: burnedpanic/accounts:latest
    container_name: accounts
    ports:
      - "8080:8080"
    deploy: 
      resources: 
        limits:
          memory: 700m
    networks:
      - burnedpanic
  loans:
    image: burnedpanic/loans:latest
    container_name: loans
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - burnedpanic
  cards:
    image: burnedpanic/cards:latest
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - burnedpanic
networks:
  burnedpanic:
    driver: "bridge"