services:
  network-deploy-service:
    networks:
      - burnedpanic

  microservices-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbit

  microservice-configserver-config:
    extends:
      service: microservices-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "admin#123"
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://database:1433;databaseName=Bank;trustServerCertificate=true;encrypt=false"
